"""Adapter-neutral BOM orchestration and policy service."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping, Optional

from jbom.common.field_parser import (
    check_fabricator_field_completeness,
    parse_fields_argument,
)
from jbom.common.options import GeneratorOptions
from jbom.config.fabricators import get_fabricator_presets
from jbom.services.bom_generator import BOMData, BOMEntry, BOMGenerator
from jbom.services.component_merge_service import (
    ComponentMergeResult,
    ComponentMergeService,
    MergedReferenceRecord,
    resolve_grouped_merge_namespace_values,
)
from jbom.services.inventory_overlay_service import InventoryOverlayService
from jbom.services.inventory_reader import InventoryReader
from jbom.services.field_listing_service import (
    get_field_names,
    get_namespaced_field_tokens,
)
from jbom.services.pcb_reader import DefaultKiCadReaderService
from jbom.services.project_component_collector import ProjectComponentCollector
from jbom.services.project_file_resolver import ProjectFileResolver
from jbom.services.schematic_reader import SchematicReader

_BOM_COMPUTED_FIELDS: tuple[str, ...] = (
    "reference",
    "quantity",
    "value",
    "description",
    "footprint",
    "manufacturer",
    "mfgpn",
    "fabricator_part_number",
    "smd",
    "lcsc",
    "package",
)


def _freeze_mapping(values: Mapping[str, Any] | None) -> Mapping[str, Any]:
    """Return an immutable copy of a metadata/options mapping."""

    return MappingProxyType(dict(values or {}))


def _normalize_text(value: str, *, field_name: str) -> str:
    """Normalize and validate a required text field."""

    normalized = str(value or "").strip()
    if not normalized:
        raise ValueError(f"{field_name} must be non-empty")
    return normalized


class BOMMode(str, Enum):
    """Result modes supported by BOM orchestration."""

    LIST_FIELDS = "list_fields"
    GENERATE = "generate"


@dataclass(frozen=True)
class BOMRequest:
    """Adapter-neutral request payload for BOM orchestration."""

    input_path: str
    fabricator: str
    fields_argument: str | None = None
    inventory_files: tuple[str, ...] = ()
    filter_config: Mapping[str, Any] = field(default_factory=dict)
    verbose: bool = False
    list_fields: bool = False

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "input_path",
            _normalize_text(self.input_path, field_name="input_path"),
        )
        object.__setattr__(
            self,
            "fabricator",
            _normalize_text(self.fabricator, field_name="fabricator"),
        )
        object.__setattr__(
            self,
            "fields_argument",
            str(self.fields_argument).strip() if self.fields_argument else None,
        )
        object.__setattr__(
            self,
            "inventory_files",
            tuple(str(path) for path in self.inventory_files),
        )
        object.__setattr__(self, "filter_config", _freeze_mapping(self.filter_config))
        object.__setattr__(self, "verbose", bool(self.verbose))
        object.__setattr__(self, "list_fields", bool(self.list_fields))


@dataclass(frozen=True)
class BOMFieldListingPayload:
    """Field-listing payload generated by BOM orchestration."""

    known_fields: Mapping[str, str]

    def __post_init__(self) -> None:
        object.__setattr__(self, "known_fields", _freeze_mapping(self.known_fields))


@dataclass(frozen=True)
class BOMGenerationPayload:
    """BOM generation payload produced by application orchestration."""

    bom_data: BOMData
    selected_fields: tuple[str, ...]
    default_output_path: Path

    def __post_init__(self) -> None:
        object.__setattr__(self, "selected_fields", tuple(self.selected_fields))


@dataclass(frozen=True)
class BOMResult:
    """Result contract emitted by BOM application orchestration."""

    mode: BOMMode
    diagnostics: tuple[str, ...] = ()
    field_listing: BOMFieldListingPayload | None = None
    generation: BOMGenerationPayload | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "diagnostics", tuple(self.diagnostics))
        if self.mode == BOMMode.LIST_FIELDS:
            if self.field_listing is None:
                raise ValueError(
                    "field_listing payload is required for list_fields mode"
                )
            if self.generation is not None:
                raise ValueError(
                    "generation payload must be empty for list_fields mode"
                )
        if self.mode == BOMMode.GENERATE:
            if self.generation is None:
                raise ValueError("generation payload is required for generate mode")
            if self.field_listing is not None:
                raise ValueError(
                    "field_listing payload must be empty for generate mode"
                )


class BOMWorkflow:
    """Application-layer BOM orchestration service."""

    def run(self, request: BOMRequest) -> BOMResult:
        """Run BOM orchestration and return adapter-neutral result payloads."""

        if request.list_fields:
            return self._list_fields(request)
        return self._generate(request)

    def _list_fields(self, request: BOMRequest) -> BOMResult:
        """Resolve dynamic field inventory for `--list-fields` behavior."""

        list_components: list = []
        list_pcb_components: list = []
        list_inventory_columns: list[str] = []

        try:
            resolver = ProjectFileResolver(
                prefer_pcb=False, target_file_type="schematic"
            )
            resolved = resolver.resolve_input(request.input_path)
            reader = SchematicReader()
            for schematic_file in resolved.get_hierarchical_files():
                list_components.extend(reader.load_components(schematic_file))

            project_context = resolved.project_context
            if (
                project_context is not None
                and project_context.pcb_file is not None
                and project_context.pcb_file.exists()
            ):
                board = DefaultKiCadReaderService().read_pcb_file(
                    project_context.pcb_file
                )
                list_pcb_components.extend(board.footprints)
        except Exception:
            pass

        for inventory_path in request.inventory_files:
            inventory_file = Path(inventory_path)
            if not inventory_file.exists():
                continue
            try:
                _, column_names = InventoryReader(inventory_file).load()
                list_inventory_columns.extend(column_names)
            except Exception:
                continue

        known_fields = build_known_bom_fields(
            list_components,
            pcb_components=list_pcb_components,
            inventory_column_names=list_inventory_columns,
        )
        return BOMResult(
            mode=BOMMode.LIST_FIELDS,
            field_listing=BOMFieldListingPayload(known_fields=known_fields),
        )

    def _generate(self, request: BOMRequest) -> BOMResult:
        """Run BOM generation sequencing independent from CLI adapter concerns."""

        diagnostics: list[str] = []
        options = GeneratorOptions(verbose=request.verbose) if request.verbose else None
        resolver = ProjectFileResolver(
            prefer_pcb=False,
            target_file_type="schematic",
            options=options,
        )
        resolved_input = resolver.resolve_input(request.input_path)

        if not resolved_input.is_schematic:
            if not os.environ.get("JBOM_QUIET"):
                diagnostics.append(
                    "Note: BOM generation requires a schematic file. "
                    f"Found {resolved_input.resolved_path.suffix} file, trying to find matching schematic."
                )
            resolved_input = resolver.resolve_for_wrong_file_type(
                resolved_input,
                "schematic",
            )
            if not os.environ.get("JBOM_QUIET"):
                diagnostics.append(
                    f"found matching schematic {resolved_input.resolved_path.name}"
                )
                diagnostics.append(
                    f"Using schematic: {resolved_input.resolved_path.name}"
                )

        if not resolved_input.project_context:
            raise ValueError("No project context available")

        project_context = resolved_input.project_context
        project_name = project_context.project_base_name
        default_output_path = (
            project_context.project_directory / f"{project_name}.bom.csv"
        )

        reader = SchematicReader(options)
        generator = BOMGenerator("value_footprint")
        hierarchical_files = resolved_input.get_hierarchical_files()
        schematic_files = list(hierarchical_files)
        if request.verbose and len(hierarchical_files) > 1:
            diagnostics.append(
                "Processing hierarchical design with "
                f"{len(hierarchical_files)} schematic files"
            )

        components = []
        for schematic_file in hierarchical_files:
            if request.verbose:
                diagnostics.append(f"Loading components from {schematic_file.name}")
            file_components = reader.load_components(schematic_file)
            components.extend(file_components)

        merge_result, merge_diagnostics = run_component_merge(
            components=components,
            schematic_files=schematic_files,
            pcb_file=project_context.pcb_file,
            verbose=request.verbose,
        )
        diagnostics.extend(merge_diagnostics)

        fabricator_presets = get_fabricator_presets(request.fabricator)
        available_fields = build_known_bom_fields(components)
        selected_fields = parse_fields_argument(
            request.fields_argument,
            available_fields,
            request.fabricator,
            fabricator_presets,
        )
        if request.verbose:
            diagnostics.append(f"Selected fields: {', '.join(selected_fields)}")

        if request.fields_argument:
            warning = check_fabricator_field_completeness(
                selected_fields,
                request.fabricator,
                fabricator_presets,
            )
            if warning:
                diagnostics.append(warning)

        filters = dict(request.filter_config)
        bom_data = generator.generate_bom_data(components, project_name, filters)
        bom_data = enrich_bom_with_merge_namespaces(bom_data, merge_result)
        bom_data = enforce_bom_device_footprints(bom_data)

        inventory_file: Path | None = None
        if request.inventory_files:
            if request.verbose:
                diagnostics.append(
                    f"Enhancing BOM with {len(request.inventory_files)} inventory file(s)"
                )
            inventory_file = Path(request.inventory_files[0])
            if not inventory_file.exists():
                raise ValueError(f"Inventory file not found: {inventory_file}")
            if len(request.inventory_files) > 1 and request.verbose:
                diagnostics.append(
                    "Note: Using primary inventory file "
                    f"{inventory_file}, multi-file enhancement coming soon"
                )

        include_inventory_dnp = not filters.get("exclude_dnp", True)
        overlay_result = InventoryOverlayService().overlay_bom_data(
            bom_data,
            inventory_file=inventory_file,
            fabricator_id=request.fabricator,
            project_name=project_name,
            include_inventory_dnp=include_inventory_dnp,
        )
        bom_data = overlay_result.bom_data
        bom_data = filter_inventory_dnp_entries(
            bom_data,
            include_inventory_dnp=include_inventory_dnp,
        )

        bom_data, smd_diagnostics = enrich_bom_smd_from_project_pcb(
            bom_data,
            project_context.pcb_file,
            verbose=request.verbose,
        )
        diagnostics.extend(smd_diagnostics)

        return BOMResult(
            mode=BOMMode.GENERATE,
            diagnostics=tuple(diagnostics),
            generation=BOMGenerationPayload(
                bom_data=bom_data,
                selected_fields=tuple(selected_fields),
                default_output_path=default_output_path,
            ),
        )


def run_component_merge(
    *,
    components: list,
    schematic_files: list[Path],
    pcb_file: Optional[Path],
    verbose: bool,
) -> tuple[ComponentMergeResult | None, tuple[str, ...]]:
    """Best-effort collector/merge execution for canonical namespace enrichment."""

    diagnostics: list[str] = []
    try:
        pcb_components = []
        if pcb_file is not None and pcb_file.exists():
            board = DefaultKiCadReaderService().read_pcb_file(pcb_file)
            pcb_components = list(board.footprints)

        collector = ProjectComponentCollector()
        project_graph = collector.collect(
            schematic_components=components,
            pcb_components=pcb_components,
            schematic_files=schematic_files,
            pcb_file=pcb_file,
        )
        merge_result = ComponentMergeService().merge(project_graph)

        if verbose:
            diagnostics.append(
                "Merge model active: "
                f"{project_graph.reference_count} references, "
                f"{len(merge_result.mismatches)} mismatch record(s)"
            )
        return merge_result, tuple(diagnostics)
    except Exception as exc:
        if verbose:
            diagnostics.append(
                f"Warning: merge model execution skipped due to error: {exc}"
            )
        return None, tuple(diagnostics)


def resolve_entry_merge_namespace_values(
    reference_records: list[MergedReferenceRecord],
) -> dict[str, str]:
    """Resolve grouped merge namespace fields for one aggregated BOM entry."""

    return resolve_grouped_merge_namespace_values(reference_records)


def enrich_bom_with_merge_namespaces(
    bom_data: BOMData,
    merge_result: ComponentMergeResult | None,
) -> BOMData:
    """Attach stable merge-model namespaces (`s:/p:/a:`) onto BOM entries."""

    if merge_result is None or not merge_result.records:
        return bom_data

    updated_entries: list[BOMEntry] = []
    any_entry_updated = False
    for entry in bom_data.entries:
        entry_merge_records = [
            merge_result.records[reference]
            for reference in entry.references
            if reference in merge_result.records
        ]
        if not entry_merge_records:
            updated_entries.append(entry)
            continue

        merge_namespace_fields = resolve_entry_merge_namespace_values(
            entry_merge_records
        )
        if not merge_namespace_fields:
            updated_entries.append(entry)
            continue

        attributes = dict(entry.attributes)
        entry_updated = False
        for field_key, field_value in merge_namespace_fields.items():
            if attributes.get(field_key) == field_value:
                continue
            attributes[field_key] = field_value
            entry_updated = True

        if not entry_updated:
            updated_entries.append(entry)
            continue

        any_entry_updated = True
        updated_entries.append(
            BOMEntry(
                references=entry.references,
                value=entry.value,
                footprint=entry.footprint,
                quantity=entry.quantity,
                lib_id=entry.lib_id,
                attributes=attributes,
            )
        )

    metadata = dict(bom_data.metadata)
    metadata.update(
        {
            "merge_model_enabled": True,
            "merge_model_reference_count": merge_result.reference_count,
            "merge_model_mismatch_count": len(merge_result.mismatches),
        }
    )
    return BOMData(
        project_name=bom_data.project_name,
        entries=updated_entries if any_entry_updated else bom_data.entries,
        metadata=metadata,
    )


def _is_truthy_inventory_dnp(value: object) -> bool:
    """Return True when an inventory DNP marker should exclude an output row."""

    if isinstance(value, bool):
        return value
    normalized = str(value or "").strip().lower()
    if not normalized:
        return False
    return normalized in {
        "1",
        "true",
        "t",
        "yes",
        "y",
        "x",
        "dnp",
        "do not populate",
    }


def _entry_has_inventory_dnp(entry: BOMEntry) -> bool:
    """Return True when a BOM entry is tagged DNP from inventory overlay data."""

    inventory_dnp = entry.attributes.get("inventory_dnp")
    if _is_truthy_inventory_dnp(inventory_dnp):
        return True
    namespaced_dnp = entry.attributes.get("i:dnp")
    if _is_truthy_inventory_dnp(namespaced_dnp):
        return True
    return False


def filter_inventory_dnp_entries(
    bom_data: BOMData,
    *,
    include_inventory_dnp: bool,
) -> BOMData:
    """Filter out inventory-DNP BOM rows unless explicitly included by policy."""

    if include_inventory_dnp:
        return bom_data

    filtered_entries = [
        entry for entry in bom_data.entries if not _entry_has_inventory_dnp(entry)
    ]
    removed_count = len(bom_data.entries) - len(filtered_entries)
    if removed_count <= 0:
        return bom_data

    metadata = dict(bom_data.metadata)
    metadata["inventory_dnp_filtered_entries"] = removed_count
    return BOMData(
        project_name=bom_data.project_name,
        entries=filtered_entries,
        metadata=metadata,
    )


def _load_pcb_smd_lookup(
    pcb_file: Optional[Path],
    *,
    verbose: bool = False,
) -> tuple[dict[str, bool], tuple[str, ...]]:
    """Return reference->is_smd lookup from a KiCad PCB file plus diagnostics."""

    diagnostics: list[str] = []
    if pcb_file is None or not pcb_file.exists():
        return {}, tuple(diagnostics)

    try:
        board = DefaultKiCadReaderService().read_pcb_file(pcb_file)
    except Exception as exc:
        if verbose:
            diagnostics.append(
                f"Warning: Could not read PCB mount metadata from {pcb_file}: {exc}"
            )
        return {}, tuple(diagnostics)

    smd_by_reference: dict[str, bool] = {}
    for footprint in board.footprints:
        reference = (footprint.reference or "").strip()
        if not reference:
            continue

        mount_type = str(footprint.attributes.get("mount_type", "")).strip().lower()
        if mount_type == "smd":
            smd_by_reference[reference] = True
        elif mount_type in {"through_hole", "through-hole", "tht"}:
            smd_by_reference[reference] = False

    return smd_by_reference, tuple(diagnostics)


def entry_smd_from_reference_lookup(
    entry: BOMEntry,
    smd_by_reference: dict[str, bool],
) -> Optional[bool]:
    """Resolve an entry-level SMD boolean from per-reference PCB metadata."""

    known_values = [
        smd_by_reference[reference]
        for reference in entry.references
        if reference in smd_by_reference
    ]
    if not known_values:
        return None
    return all(known_values)


def enrich_bom_smd_from_project_pcb(
    bom_data: BOMData,
    pcb_file: Optional[Path],
    *,
    verbose: bool = False,
) -> tuple[BOMData, tuple[str, ...]]:
    """Populate missing BOM `smd` attributes from PCB mount metadata."""

    smd_by_reference, diagnostics = _load_pcb_smd_lookup(pcb_file, verbose=verbose)
    if not smd_by_reference:
        return bom_data, diagnostics

    updated = False
    enriched_entries: list[BOMEntry] = []

    for entry in bom_data.entries:
        current_smd = str(entry.attributes.get("smd", "")).strip()
        if current_smd:
            enriched_entries.append(entry)
            continue

        resolved = entry_smd_from_reference_lookup(entry, smd_by_reference)
        if resolved is None:
            enriched_entries.append(entry)
            continue

        attrs = dict(entry.attributes)
        attrs["smd"] = resolved
        enriched_entries.append(
            BOMEntry(
                references=entry.references,
                value=entry.value,
                footprint=entry.footprint,
                quantity=entry.quantity,
                lib_id=entry.lib_id,
                attributes=attrs,
            )
        )
        updated = True

    if not updated:
        return bom_data, diagnostics

    metadata = dict(bom_data.metadata)
    metadata["pcb_mount_metadata_used"] = True
    return (
        BOMData(
            project_name=bom_data.project_name,
            entries=enriched_entries,
            metadata=metadata,
        ),
        diagnostics,
    )


def _entry_has_namespaced_field(entry: BOMEntry, namespaced_field: str) -> bool:
    """Return True when an entry explicitly carries a given namespaced field."""

    normalized_target = namespaced_field.strip().lower()
    for attribute_key in entry.attributes.keys():
        normalized_key = str(attribute_key or "").strip().lower()
        if normalized_key == normalized_target:
            return True
    return False


def _resolve_entry_device_footprint(entry: BOMEntry) -> str:
    """Resolve concrete device footprint with PCB-first precedence."""

    has_pcb_footprint = _entry_has_namespaced_field(entry, "p:footprint")
    pcb_footprint = str(entry.attributes.get("p:footprint", "") or "").strip()
    if has_pcb_footprint:
        return pcb_footprint

    schematic_footprint = str(entry.attributes.get("s:footprint", "") or "").strip()
    fallback_footprint = str(entry.footprint or "").strip()
    for candidate in (schematic_footprint, fallback_footprint):
        if _is_concrete_footprint(candidate):
            return str(candidate).strip()
    for candidate in (schematic_footprint, fallback_footprint):
        normalized_candidate = str(candidate or "").strip()
        if normalized_candidate:
            return normalized_candidate
    return ""


def _is_concrete_footprint(value: str) -> bool:
    """Return True when a footprint token is concrete enough for BOM devices."""

    token = str(value or "").strip()
    if not token or token == "~":
        return False
    if "*" in token or "?" in token:
        return False
    return True


def enforce_bom_device_footprints(bom_data: BOMData) -> BOMData:
    """Enforce concrete footprint availability for BOM/device generation."""

    missing_references: list[str] = []
    updated_entries: list[BOMEntry] = []
    changed = False

    for entry in bom_data.entries:
        resolved_footprint = _resolve_entry_device_footprint(entry)
        if not _is_concrete_footprint(resolved_footprint):
            missing_references.append(entry.references_string)
            updated_entries.append(entry)
            continue

        if resolved_footprint == entry.footprint:
            updated_entries.append(entry)
            continue

        changed = True
        updated_entries.append(
            BOMEntry(
                references=entry.references,
                value=entry.value,
                footprint=resolved_footprint,
                quantity=entry.quantity,
                lib_id=entry.lib_id,
                attributes=dict(entry.attributes),
            )
        )

    if missing_references:
        refs = "; ".join(missing_references)
        raise ValueError(
            "BOM generation requires concrete component footprints; "
            f"missing/unresolved footprint for: {refs}"
        )

    if not changed:
        return bom_data

    metadata = dict(bom_data.metadata)
    metadata["device_footprint_contract"] = "enforced"
    metadata["device_footprint_precedence"] = "p>s"
    return BOMData(
        project_name=bom_data.project_name,
        entries=updated_entries,
        metadata=metadata,
    )


def build_known_bom_fields(
    components: list,
    *,
    pcb_components: list | None = None,
    inventory_column_names: list[str] | None = None,
) -> dict[str, str]:
    """Return known BOM fields from computed contract plus discovered source fields."""

    fields = {field_name: "Computed BOM field" for field_name in _BOM_COMPUTED_FIELDS}
    for source_token in get_namespaced_field_tokens(
        schematic_components=components,
        pcb_components=pcb_components or [],
        inventory_column_names=inventory_column_names or [],
    ):
        fields[source_token] = "Discovered source field"

    for field_name in get_field_names(
        schematic_components=components,
        pcb_components=pcb_components or [],
        inventory_column_names=inventory_column_names or [],
        source="all",
    ):
        fields.setdefault(field_name, "Discovered field")

    return fields


__all__ = [
    "BOMWorkflow",
    "BOMFieldListingPayload",
    "BOMGenerationPayload",
    "BOMMode",
    "BOMRequest",
    "BOMResult",
    "build_known_bom_fields",
    "enforce_bom_device_footprints",
    "enrich_bom_smd_from_project_pcb",
    "enrich_bom_with_merge_namespaces",
    "entry_smd_from_reference_lookup",
    "filter_inventory_dnp_entries",
    "run_component_merge",
]
