"""Adapter-neutral POS orchestration service."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping

from jbom.common.field_parser import parse_fields_argument
from jbom.common.fields import field_to_header
from jbom.common.options import GeneratorOptions, PlacementOptions
from jbom.config.fabricators import FabricatorConfig, get_fabricator_default_fields
from jbom.services.component_merge_service import (
    ComponentMergeResult,
    ComponentMergeService,
)
from jbom.services.fabricator_projection_service import FabricatorProjectionService
from jbom.services.field_listing_service import (
    get_field_names,
    get_namespaced_field_tokens,
)
from jbom.services.pcb_reader import DefaultKiCadReaderService
from jbom.services.pos_generator import POSGenerator
from jbom.services.project_component_collector import ProjectComponentCollector
from jbom.services.project_file_resolver import ProjectFileResolver
from jbom.services.schematic_reader import SchematicReader

_POS_COMPUTED_FIELDS: tuple[str, ...] = (
    "reference",
    "x",
    "y",
    "rotation",
    "side",
    "footprint",
    "package",
    "value",
    "fabricator_part_number",
)

DiagnosticEmitter = Callable[[str], None]


@dataclass(frozen=True)
class POSOrchestrationRequest:
    """Adapter-neutral POS orchestration request data."""

    input_path: str
    output: str = ""
    fabricator: str = "generic"
    smd_only: bool = False
    layer: str = ""
    origin: str = "board"
    fields: str | None = None
    list_fields: bool = False
    include_dnp: bool = False
    verbose: bool = False
    quiet: bool = False


@dataclass(frozen=True)
class POSFieldListingPayload:
    """Field-listing payload generated by orchestration."""

    known_fields: Mapping[str, str]
    default_fields: tuple[str, ...]


@dataclass(frozen=True)
class POSOutputPayload:
    """Resolved POS output payload produced by orchestration."""

    pos_data: tuple[dict[str, Any], ...]
    selected_fields: tuple[str, ...]
    headers: tuple[str, ...]
    fabricator: str
    fabricator_config: FabricatorConfig | None
    default_output_path: Path


@dataclass(frozen=True)
class POSOrchestrationResult:
    """Orchestration outcome containing either listing or output payload data."""

    field_listing: POSFieldListingPayload | None = None
    output_payload: POSOutputPayload | None = None


def _noop_diagnostic(_message: str) -> None:
    """Default no-op diagnostic sink."""

    return


def run_pos_component_merge(
    *,
    schematic_components: list[Any],
    pcb_components: list[Any],
    schematic_files: list[Path],
    pcb_file: Path | None,
    verbose: bool,
    emit_diagnostic: DiagnosticEmitter,
) -> ComponentMergeResult | None:
    """Best-effort collector/merge execution for POS namespace enrichment."""

    try:
        collector = ProjectComponentCollector()
        project_graph = collector.collect(
            schematic_components=schematic_components,
            pcb_components=pcb_components,
            schematic_files=schematic_files,
            pcb_file=pcb_file,
        )
        merge_service = ComponentMergeService()
        merge_result = merge_service.merge(project_graph)
        if verbose:
            emit_diagnostic(
                "Merge model active: "
                f"{project_graph.reference_count} references, "
                f"{len(merge_result.mismatches)} mismatch record(s)"
            )
        return merge_result
    except Exception as exc:
        if verbose:
            emit_diagnostic(
                f"Warning: merge model execution skipped due to error: {exc}"
            )
        return None


def enrich_pos_with_merge_namespaces(
    pos_data: list[dict[str, Any]],
    merge_result: ComponentMergeResult | None,
) -> list[dict[str, Any]]:
    """Attach merge namespace fields (`s:/p:/a:`) onto POS row dictionaries."""

    if merge_result is None or not merge_result.records:
        return pos_data

    enriched_rows: list[dict[str, Any]] = []
    any_updated = False
    for row in pos_data:
        reference = str(row.get("reference", "")).strip()
        merge_record = merge_result.records.get(reference)
        if merge_record is None:
            enriched_rows.append(row)
            continue

        merged_fields: dict[str, str] = {}
        merged_fields.update(merge_record.source_fields)
        merged_fields.update(merge_record.annotated_fields)
        if not merged_fields:
            enriched_rows.append(row)
            continue

        updated_row = dict(row)
        row_updated = False
        for field_key, field_value in merged_fields.items():
            normalized_value = str(field_value or "").strip()
            if not normalized_value:
                continue
            if str(updated_row.get(field_key, "")).strip() == normalized_value:
                continue
            updated_row[field_key] = normalized_value
            row_updated = True

        if row_updated:
            any_updated = True
            enriched_rows.append(updated_row)
        else:
            enriched_rows.append(row)

    return enriched_rows if any_updated else pos_data


def get_available_pos_fields(
    *,
    schematic_components: list | None = None,
    pcb_components: list | None = None,
    inventory_column_names: list[str] | None = None,
) -> dict[str, str]:
    """Get available POS fields with descriptions."""

    known_fields = {
        field_name: "Computed POS field" for field_name in _POS_COMPUTED_FIELDS
    }
    for source_token in get_namespaced_field_tokens(
        schematic_components=schematic_components or [],
        pcb_components=pcb_components or [],
        inventory_column_names=inventory_column_names or [],
    ):
        known_fields[source_token] = "Discovered source field"
    for field_name in get_field_names(
        schematic_components=schematic_components or [],
        pcb_components=pcb_components or [],
        inventory_column_names=inventory_column_names or [],
        source="all",
    ):
        known_fields.setdefault(field_name, "Discovered field")
    return known_fields


def resolve_default_pos_fields(fabricator: str) -> list[str]:
    """Resolve POS default output fields from fabricator profile metadata."""

    fabricator_defaults = get_fabricator_default_fields(fabricator, "pos")
    if fabricator_defaults:
        return list(fabricator_defaults)

    generic_defaults = get_fabricator_default_fields("generic", "pos")
    if generic_defaults:
        return list(generic_defaults)

    raise ValueError(
        "No POS default fields found in fabricator profile configuration for "
        f"'{fabricator}' or 'generic'"
    )


def resolve_pos_output_projection(
    *,
    selected_fields: list[str] | None,
    fabricator: str,
    user_specified_fields: bool,
    projection_service: FabricatorProjectionService | None = None,
) -> tuple[list[str], list[str], FabricatorConfig | None]:
    """Resolve effective POS fields, headers, and fabricator config."""

    effective_fields = list(selected_fields) if selected_fields else []
    if not effective_fields:
        effective_fields = resolve_default_pos_fields(fabricator)

    service = projection_service or FabricatorProjectionService()
    projection = service.build_projection(
        fabricator_id=fabricator,
        output_type="pos",
        selected_fields=effective_fields,
    )

    headers = (
        [field_to_header(field) for field in effective_fields]
        if user_specified_fields
        else list(projection.headers)
    )
    return effective_fields, headers, projection.fabricator_config


def _is_truthy_dnp_marker(value: object) -> bool:
    """Return True when a DNP marker should exclude a POS row."""

    if isinstance(value, bool):
        return value
    normalized = str(value or "").strip().lower()
    if not normalized:
        return False
    return normalized in {
        "1",
        "true",
        "t",
        "yes",
        "y",
        "x",
        "dnp",
        "do not populate",
    }


def _entry_has_dnp_marker(entry: dict[str, Any]) -> bool:
    """Return True when a POS row contains schematic/inventory DNP flags."""

    for key in ("dnp", "s:dnp", "i:dnp"):
        if _is_truthy_dnp_marker(entry.get(key)):
            return True
    return False


def apply_pos_dnp_filter(
    pos_data: list[dict[str, Any]],
    *,
    include_dnp: bool,
) -> list[dict[str, Any]]:
    """Filter DNP rows from POS data unless `include_dnp` is enabled."""

    if include_dnp:
        return pos_data
    return [entry for entry in pos_data if not _entry_has_dnp_marker(entry)]


def _parse_requested_field_tokens(raw_fields: str) -> list[str]:
    """Parse and validate raw `--fields` token text."""

    raw_tokens = [token.strip() for token in raw_fields.split(",")]
    parsed_tokens: list[str] = []
    for token in raw_tokens:
        if not token:
            continue
        if len(token) >= 2 and token[0] == token[-1] and token[0] in ("'", '"'):
            token = token[1:-1].strip()
        if token:
            parsed_tokens.append(token)
    return parsed_tokens


class POSOrchestrationService:
    """Application-layer POS orchestration service."""

    def orchestrate(
        self,
        request: POSOrchestrationRequest,
        *,
        emit_diagnostic: DiagnosticEmitter | None = None,
    ) -> POSOrchestrationResult:
        """Execute POS orchestration for listing or generation flows."""

        diagnostic_sink = emit_diagnostic or _noop_diagnostic

        if request.list_fields:
            return POSOrchestrationResult(
                field_listing=self._orchestrate_field_listing(request)
            )
        return POSOrchestrationResult(
            output_payload=self._orchestrate_output(
                request,
                emit_diagnostic=diagnostic_sink,
            )
        )

    def _orchestrate_field_listing(
        self,
        request: POSOrchestrationRequest,
    ) -> POSFieldListingPayload:
        """Build POS field-listing data from best-effort project discovery."""

        gen_options = GeneratorOptions(verbose=request.verbose) if request.verbose else None
        list_pcb_components: list[Any] = []
        list_schematic_components: list[Any] = []
        try:
            list_resolver = ProjectFileResolver(
                prefer_pcb=True,
                target_file_type="pcb",
                options=gen_options,
            )
            list_resolved = list_resolver.resolve_input(request.input_path)
            if not list_resolved.is_pcb:
                list_resolved = list_resolver.resolve_for_wrong_file_type(
                    list_resolved,
                    "pcb",
                )
            list_pcb_path = list_resolved.resolved_path
            if list_pcb_path.exists():
                list_board = DefaultKiCadReaderService().read_pcb_file(list_pcb_path)
                list_pcb_components = list(list_board.footprints)
            list_project_context = list_resolved.project_context
            if list_project_context is not None:
                list_schematic_files = [
                    file_path
                    for file_path in list_project_context.get_hierarchical_schematic_files()
                    if file_path.suffix.lower() == ".kicad_sch" and file_path.exists()
                ]
                list_schematic_reader = SchematicReader(gen_options)
                for schematic_file in list_schematic_files:
                    list_schematic_components.extend(
                        list_schematic_reader.load_components(schematic_file)
                    )
        except Exception:
            pass

        known_fields = get_available_pos_fields(
            schematic_components=list_schematic_components or None,
            pcb_components=list_pcb_components or None,
        )
        default_fields = tuple(get_fabricator_default_fields(request.fabricator, "pos") or ())
        return POSFieldListingPayload(
            known_fields=known_fields,
            default_fields=default_fields,
        )

    def _orchestrate_output(
        self,
        request: POSOrchestrationRequest,
        *,
        emit_diagnostic: DiagnosticEmitter,
    ) -> POSOutputPayload:
        """Execute POS orchestration and return adapter-ready output payloads."""

        gen_options = GeneratorOptions(verbose=request.verbose) if request.verbose else None
        resolver = ProjectFileResolver(
            prefer_pcb=True,
            target_file_type="pcb",
            options=gen_options,
        )
        resolved_input = resolver.resolve_input(request.input_path)

        if not resolved_input.is_pcb:
            if not request.quiet:
                emit_diagnostic(
                    "Note: POS generation requires a PCB file. "
                    f"Found {resolved_input.resolved_path.suffix} file, trying to find matching PCB."
                )
            resolved_input = resolver.resolve_for_wrong_file_type(resolved_input, "pcb")
            if not request.quiet:
                emit_diagnostic(f"found matching PCB {resolved_input.resolved_path.name}")
                emit_diagnostic(f"Using PCB: {resolved_input.resolved_path.name}")

        pcb_file = resolved_input.resolved_path
        if not resolved_input.project_context:
            raise ValueError("No project context available")

        project_context = resolved_input.project_context
        project_name = project_context.project_base_name
        default_output_path = project_context.project_directory / f"{project_name}.pos.csv"

        try:
            hier_files = list(project_context.get_hierarchical_schematic_files())
            if hier_files and len(hier_files) > 1:
                emit_diagnostic("Processing hierarchical design")
        except Exception:
            pass

        placement_options = PlacementOptions(
            origin=request.origin,
            smd_only=request.smd_only,
            layer_filter=request.layer or None,
        )
        if request.verbose and request.include_dnp:
            emit_diagnostic("Including DNP components in POS output")

        board = DefaultKiCadReaderService().read_pcb_file(pcb_file)
        pos_data = POSGenerator(placement_options).generate_pos_data(board)

        schematic_files: list[Path] = []
        try:
            discovered_files = list(project_context.get_hierarchical_schematic_files())
            schematic_files = [
                file_path
                for file_path in discovered_files
                if file_path.suffix.lower() == ".kicad_sch" and file_path.exists()
            ]
        except Exception as exc:
            if request.verbose:
                emit_diagnostic(
                    "Warning: could not load schematic files for merge enrichment: "
                    f"{exc}"
                )

        schematic_components: list[Any] = []
        if schematic_files:
            schematic_reader = SchematicReader(gen_options)
            for schematic_file in schematic_files:
                try:
                    schematic_components.extend(
                        schematic_reader.load_components(schematic_file)
                    )
                except Exception as exc:
                    if request.verbose:
                        emit_diagnostic(
                            "Warning: skipping schematic source for merge enrichment "
                            f"({schematic_file}): {exc}"
                        )

        merge_result = run_pos_component_merge(
            schematic_components=schematic_components,
            pcb_components=list(board.footprints),
            schematic_files=schematic_files,
            pcb_file=pcb_file,
            verbose=request.verbose,
            emit_diagnostic=emit_diagnostic,
        )
        pos_data = enrich_pos_with_merge_namespaces(pos_data, merge_result)
        pos_data = apply_pos_dnp_filter(pos_data, include_dnp=request.include_dnp)

        available_pos_fields = get_available_pos_fields(
            schematic_components=schematic_components,
            pcb_components=list(board.footprints),
        )

        if request.fields is not None and not _parse_requested_field_tokens(request.fields):
            raise ValueError("--fields parameter cannot be empty")

        user_specified_fields = request.fields is not None and request.fabricator == "generic"
        selected_fields = parse_fields_argument(
            request.fields,
            available_pos_fields,
            request.fabricator,
            None,
            context="pos",
        )
        effective_fields, headers, fabricator_config = resolve_pos_output_projection(
            selected_fields=selected_fields,
            fabricator=request.fabricator,
            user_specified_fields=user_specified_fields,
        )
        return POSOutputPayload(
            pos_data=tuple(pos_data),
            selected_fields=tuple(effective_fields),
            headers=tuple(headers),
            fabricator=request.fabricator,
            fabricator_config=fabricator_config,
            default_output_path=default_output_path,
        )


__all__ = [
    "POSFieldListingPayload",
    "POSOrchestrationRequest",
    "POSOrchestrationResult",
    "POSOrchestrationService",
    "POSOutputPayload",
    "apply_pos_dnp_filter",
    "enrich_pos_with_merge_namespaces",
    "get_available_pos_fields",
    "resolve_default_pos_fields",
    "resolve_pos_output_projection",
    "run_pos_component_merge",
]
